apiVersion: v2
name: nginx-app
description: A simple Helm chart that deploys an nginx server with an Ingress
type: application
version: 0.1.0
appVersion: "1.27.0"
keywords:
  - nginx
  - web
  - ingress
maintainers:
  - name: roadpass
